#pragma once

#define USB_DEVICE_ONLY
#define USE_STATIC_OPTIONS (USB_DEVICE_OPT_FULLSPEED | USB_OPT_REG_ENABLED | USB_OPT_AUTO_PLL)
#define FIXED_CONTROL_ENDPOINT_SIZE 64
#define FIXED_NUM_CONFIGURATIONS 1

#define INTERRUPT_CONTROL_ENDPOINT
#define NO_DEVICE_REMOTE_WAKEUP
#define NO_DEVICE_SELF_POWER
